### ISSUE TITLE
Black screen after minimizing app

### ISSUE THREAD

**Issue by StrikeNP** [OpenMW/android-port#43]
Switching apps and coming back will turn the screen black, while leaving the game running (audio still plays)

**Comment by bdd4329** [comment]
I'm also experiencing this problem on my Nvidia Shield. This makes the game unplayable because if I happen to bump the home button it will return to the home menu and I can't go back and save the game due to the black screen.

It would be nice to require the home button to be pressed twice in quick succession before the game would return to the home screen.

**Comment by terabyte25** [comment]
Duplicates #6, can we close this?

**Comment by StrikeNP** [comment]
@terabyte25 I agree that those issues look the same, my bad. 
Closing ticket as a duplicate to #6, follow that ticket for progress on this issue.

**Comment by terabyte25** [comment]
Thanks.
