### ISSUE TITLE
OpenSceneGraph Fork - white textures glitch

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#61]
Mate 9 / AOSP 9
![Image5430008402391800362](https://user-images.githubusercontent.com/2282799/56672036-5eb12d80-66be-11e9-96dc-34bcd45133ef.jpg)

No issue on "Mainline".

**Comment by terabyte25** [comment]
I've been having this problem as well for a long time too. Does @xyzz know it doesn't work properly as well?

**Comment by licaon-kter** [comment]
I've read the Fork has some performance gains, is this still true, what's the reason for its existence?

**Comment by xyzz** [comment]
Yeah it's broken. I don't know if there are any performance gains. The reason for adding it initially was so that if there's some issue with the game we can check whether it's caused by osg/openmw/or openmw using osg the wrong way. But I'll probably remove it soon since it's completely useless in its current state (texture bugs etc), no one's updating it, and it causes the apk to increase 2x in size for no good reason.

**Comment by licaon-kter** [comment]
@xyzz Any chance to get it separated at build time? Eg. An option in `build.sh`

Looks like OSG takes most of the build time and we're building it twice actually, but then Fork is not getting used anyway if it glitches.

**Comment by xyzz** [comment]
No, I'll just remove it. I'd rather not have more build configurations than needed.

**Comment by licaon-kter** [comment]
I was going to try my hand at it later, but thanks thene :)
